### ISSUE TITLE
Converting dtype of hdf5 file

### ISSUE THREAD

**Issue by raghavgurbaxani** [mortenpi/hdf5#1]
Hi 

Is it possible to convert the data type of a h5 file ? 

I want to convert my machine learning model which is stored in h5 file format from float 32 to float 16 or to int 8.

Would appreciate your help on the matter.

**Comment by mortenpi** [comment]
Sorry, I can't really help. This is not an official repository for HDF5. I just uploaded the sources from a tarball at some point. You should probably check out the HDF5 group's home page (https://www.hdfgroup.org/) to see what they have available for user support.
